---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: agate
description: A custom image of Bazzite for personal needs.

base-image: ghcr.io/ublue-os/bazzite-dx-nvidia
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - from-file: common-packages.yml
  - from-file: common-flatpaks.yml
  - from-file: common-theming.yml
  - from-file: common-branding.yml
  - from-file: common-development.yml

  - type: signing
labels:
  "org.opencontainers.image.title": "Agate"
  "org.opencontainers.image.source": "https://os.fpt.icu/"
  "org.opencontainers.image.url": "https://os.fpt.icu/"
  "org.opencontainers.image.documentation": "https://os.fpt.icu/"
  "org.opencontainers.image.description": "A custom image of Bazzite for personal needs."
  "org.opencontainers.image.vendor": "fptbb"
  "org.opencontainers.image.base.name": "quay.io/fptbb/agate:latest"
  "io.artifacthub.package.readme-url": "https://raw.githubusercontent.com/fptbb/agate/refs/heads/main/README.md"
  "io.artifacthub.package.logo-url": "https://raw.githubusercontent.com/fptbb/agate/main/files/system/usr/share/pixmaps/fp-logo.png"
  "io.artifacthub.package.maintainers": '[{\"name\": \"fptbb\", \"email\": \"lucas@fptbb.com\"}]'
  "io.artifacthub.package.prerelease": "false"
  "io.artifacthub.package.keywords": "fp-os, bootc, ostree, ublue, universal-blue, blue-build, agate"
  "io.artifacthub.package.deprecated": "false"
