---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: fp-os-next
# description will be included in the image's metadata
description: A custom image of Bazzite for personal needs.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-dx-nvidia
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      cleanup: true
      files:
        - nordvpn.repo
        - tailscale.repo
        - netbird.repo
        - megasync.repo
      copr:
        - fptbb/fp-os-meta
        - jloehel/yadm
        - bigjapka/VeraCrypt
        - psygreg/linuxtoys
        - zeno/scrcpy
      keys:
        - https://repo.nordvpn.com/gpg/nordvpn_public.asc
        - https://pkgs.netbird.io/yum/repodata/repomd.xml.key
        - https://mega.nz/linux/repo/Fedora_%OS_VERSION%/repodata/repomd.xml.key
    install:
      packages:
        - fp-os-meta
        - yadm
        - veracrypt
        - nordvpn
        - tailscale
        - netbird
        - netbird-ui
        - linuxtoys
        - scrcpy
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - app.zen_browser.zen
          - com.bitwarden.desktop
          - com.dec05eba.gpu_screen_recorder
          - com.github.Matoking.protontricks
          - com.github.tchx84.Flatseal
          - com.heroicgameslauncher.hgl
          - com.jetpackduba.Gitnuro
          - com.obsproject.Studio
          - com.spotify.Client
          - com.usebottles.bottles
          - eu.ithz.umftpd
          - io.github.equicord.equibop
          - io.github.martinrotter.rssguard
          - io.github.peazip.PeaZip
          - io.github.ryubing.Ryujinx
          - io.mrarm.mcpelauncher
          - io.podman_desktop.PodmanDesktop
          - io.qt.QtCreator
          - it.mijorus.gearlever
          - md.obsidian.Obsidian
          - net.epson.epsonscan2
          - org.audacityteam.Audacity
          - org.gimp.GIMP
          - org.gnome.Boxes
          - org.kde.digikam
          - org.kde.haruna
          - org.mozilla.Thunderbird
          - org.onlyoffice.desktopeditors
          - org.pipewire.Helvum
          - org.prismlauncher.PrismLauncher
          - org.qbittorrent.qBittorrent
          - org.upnproutercontrol.UPnPRouterControl
          - org.vinegarhq.Sober
          - org.vinegarhq.Vinegar
          - rest.insomnia.Insomnia
      - scope: user # Also add Flathub user repo, but no user packages
  - type: systemd
    system:
      enabled:
        - nordvpnd
        - tailscaled
        - netbird
  - type: os-release
    properties:
      ID: fp_os
      VARIANT_ID: fp-os
      NAME: Fp OS
      PRETTY_NAME: Fp OS
      HOME_URL: https://os.fpt.icu
  - type: initramfs
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
