---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: fp-os
description: A custom image of Bazzite for personal needs.

base-image: ghcr.io/ublue-os/bazzite-dx-nvidia
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - from-file: common-packages.yml
  - from-file: common-flatpaks.yml
  - from-file: common-branding.yml

  - type: signing
